CREATE TABLE [dbo].[Order]
(
Id	NVARCHAR(50) NOT NULL,	
Customer	NVARCHAR(50) NOT NULL,
OrderNumber	NVARCHAR	(100)	NOT NULL,
OrderStatus	NVARCHAR (50)  NULL  ,		
OrderDate	DATETIME NOT NULL DEFAULT GETDATE(),
TotalAmount	DECIMAL	(12 , 2)	NOT NULL	DEFAULT 0,
TotalDiscount	DECIMAL	(12 , 2) NOT NULL,
CreatedDate	DATETIME2 NOT NULL DEFAULT GETDATE(),
CreatedBy NVARCHAR(128) NOT NULL,
UpdatedDate DATETIME2 NULL,
UpdatedBy NVARCHAR(128) NULL,
CONSTRAINT PK_Order PRIMARY KEY(Id)
)
